// <auto-generated />
using Assignment4_NASA.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Assignment4_NASA2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Assignment4_NASA.Models.Apod", b =>
                {
                    b.Property<string>("date")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("explanation");

                    b.Property<string>("hdurl");

                    b.Property<string>("media_type");

                    b.Property<string>("service_version");

                    b.Property<string>("title");

                    b.Property<string>("url");

                    b.HasKey("date");

                    b.ToTable("apod");
                });
#pragma warning restore 612, 618
        }
    }
}
